
Template #2: The project is intended to by used as a library with examples


language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/httpget/httpget.ino
    - PLATFORMIO_CI_SRC=examples/test_ftp/test_ftp.ino
    - PLATFORMIO_CI_SRC=examples/sodaq_wunderground/sodaq_wunderground.ino

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio ci --lib="." --lib="examples/sodaq_wunderground/" --board=mayfly --board=sodaq_mbili
