language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/httpget/httpget.ino
    - PLATFORMIO_CI_SRC=examples/httppost/httppost.ino
    - PLATFORMIO_CI_SRC=examples/test_ftp/test_ftp.ino

install:
    - pip install -U platformio
    - platformio update
    - pio lib -g install https://github.com/EnviroDIY/Sodaq_DS3231.git

script:
    - platformio ci --lib="." --board=mayfly --board=sodaq_mbili  --board=sodaq_ndogo  --board=sodaq_autonomo
